steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/apps/spotify-suggestions:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/apps/spotify-suggestions:latest',
      '-f', 'cloudrun/spotify-suggestions/Dockerfile',
      'cloudrun/spotify-suggestions'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/apps/spotify-suggestions:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/apps/spotify-suggestions:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run','deploy','spotify-suggestions',
      '--image','us-central1-docker.pkg.dev/$PROJECT_ID/apps/spotify-suggestions:$COMMIT_SHA',
      '--region','us-central1',
      '--platform','managed',
      '--allow-unauthenticated'
    ]

logsBucket: gs://sp-playlist-builder-1968-cloudbuild-logs-us-central1
